apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: producer-app-for-stg-kafka-network-policy
spec:
  podSelector:
    matchLabels:
      app: producer-app-for-stg-kafka
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 100.99.122.207/32
      ports:
        - protocol: TCP
          port: 9092
    - to:
        - ipBlock:
            cidr: 100.99.122.209/32
      ports:
        - protocol: TCP
          port: 9092
